// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using TableReservationSystem.Data;

namespace TableReservationSystem.Migrations
{
    [DbContext(typeof(TableReservationSystemContext))]
    partial class TableReservationSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TableReservationSystem.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("TableID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TableID");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("TableReservationSystem.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("HighChair")
                        .HasColumnType("bit");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<int>("Shape")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<bool>("Window")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Table");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HighChair = true,
                            Seats = 2,
                            Shape = 1,
                            Size = 0,
                            Window = false
                        },
                        new
                        {
                            Id = 2,
                            HighChair = true,
                            Seats = 4,
                            Shape = 1,
                            Size = 1,
                            Window = true
                        },
                        new
                        {
                            Id = 3,
                            HighChair = false,
                            Seats = 5,
                            Shape = 2,
                            Size = 1,
                            Window = true
                        },
                        new
                        {
                            Id = 4,
                            HighChair = false,
                            Seats = 4,
                            Shape = 2,
                            Size = 1,
                            Window = true
                        },
                        new
                        {
                            Id = 5,
                            HighChair = false,
                            Seats = 4,
                            Shape = 1,
                            Size = 1,
                            Window = false
                        },
                        new
                        {
                            Id = 6,
                            HighChair = false,
                            Seats = 4,
                            Shape = 1,
                            Size = 1,
                            Window = false
                        },
                        new
                        {
                            Id = 7,
                            HighChair = false,
                            Seats = 4,
                            Shape = 1,
                            Size = 1,
                            Window = false
                        },
                        new
                        {
                            Id = 8,
                            HighChair = true,
                            Seats = 4,
                            Shape = 3,
                            Size = 1,
                            Window = false
                        },
                        new
                        {
                            Id = 9,
                            HighChair = true,
                            Seats = 4,
                            Shape = 3,
                            Size = 1,
                            Window = false
                        },
                        new
                        {
                            Id = 10,
                            HighChair = true,
                            Seats = 4,
                            Shape = 3,
                            Size = 1,
                            Window = false
                        },
                        new
                        {
                            Id = 11,
                            HighChair = true,
                            Seats = 4,
                            Shape = 1,
                            Size = 1,
                            Window = false
                        },
                        new
                        {
                            Id = 12,
                            HighChair = true,
                            Seats = 4,
                            Shape = 1,
                            Size = 1,
                            Window = false
                        },
                        new
                        {
                            Id = 14,
                            HighChair = false,
                            Seats = 2,
                            Shape = 3,
                            Size = 0,
                            Window = false
                        },
                        new
                        {
                            Id = 15,
                            HighChair = true,
                            Seats = 2,
                            Shape = 3,
                            Size = 0,
                            Window = false
                        },
                        new
                        {
                            Id = 16,
                            HighChair = false,
                            Seats = 2,
                            Shape = 3,
                            Size = 0,
                            Window = false
                        },
                        new
                        {
                            Id = 17,
                            HighChair = false,
                            Seats = 2,
                            Shape = 3,
                            Size = 0,
                            Window = false
                        },
                        new
                        {
                            Id = 18,
                            HighChair = false,
                            Seats = 2,
                            Shape = 3,
                            Size = 0,
                            Window = false
                        },
                        new
                        {
                            Id = 19,
                            HighChair = false,
                            Seats = 2,
                            Shape = 3,
                            Size = 0,
                            Window = false
                        },
                        new
                        {
                            Id = 20,
                            HighChair = true,
                            Seats = 12,
                            Shape = 1,
                            Size = 2,
                            Window = true
                        },
                        new
                        {
                            Id = 21,
                            HighChair = false,
                            Seats = 1,
                            Shape = 0,
                            Size = 0,
                            Window = false
                        },
                        new
                        {
                            Id = 22,
                            HighChair = false,
                            Seats = 1,
                            Shape = 0,
                            Size = 0,
                            Window = false
                        },
                        new
                        {
                            Id = 23,
                            HighChair = false,
                            Seats = 1,
                            Shape = 0,
                            Size = 0,
                            Window = false
                        },
                        new
                        {
                            Id = 24,
                            HighChair = false,
                            Seats = 1,
                            Shape = 0,
                            Size = 0,
                            Window = false
                        },
                        new
                        {
                            Id = 25,
                            HighChair = false,
                            Seats = 1,
                            Shape = 0,
                            Size = 0,
                            Window = false
                        },
                        new
                        {
                            Id = 26,
                            HighChair = false,
                            Seats = 1,
                            Shape = 0,
                            Size = 0,
                            Window = false
                        },
                        new
                        {
                            Id = 27,
                            HighChair = false,
                            Seats = 1,
                            Shape = 0,
                            Size = 0,
                            Window = false
                        },
                        new
                        {
                            Id = 28,
                            HighChair = false,
                            Seats = 1,
                            Shape = 0,
                            Size = 0,
                            Window = false
                        },
                        new
                        {
                            Id = 29,
                            HighChair = false,
                            Seats = 1,
                            Shape = 0,
                            Size = 0,
                            Window = false
                        },
                        new
                        {
                            Id = 30,
                            HighChair = false,
                            Seats = 1,
                            Shape = 0,
                            Size = 0,
                            Window = false
                        },
                        new
                        {
                            Id = 31,
                            HighChair = false,
                            Seats = 1,
                            Shape = 0,
                            Size = 0,
                            Window = false
                        },
                        new
                        {
                            Id = 32,
                            HighChair = false,
                            Seats = 1,
                            Shape = 0,
                            Size = 0,
                            Window = false
                        });
                });

            modelBuilder.Entity("TableReservationSystem.Models.Reservation", b =>
                {
                    b.HasOne("TableReservationSystem.Models.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableID");

                    b.Navigation("Table");
                });
#pragma warning restore 612, 618
        }
    }
}
